#!/usr/bin/env bash
# transfers a file from our client to a server
if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    SSH_KEY=$4
	FILE_PATH=$1
	USERNAME=$3
	IP=$2
    scp -i $SSH_KEY -o StrictHostKeyChecking=no $FILE_PATH $USERNAME@$IP:~/
fi
