#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 429686-web-1 54.236.30.207:80 check\n\tserver 429686-web-2 3.85.168.24:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
