#!/usr/bin/env bash
# Nginx user instead of root

sudo service nginx stop
echo "user nginx;" >> /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
